### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by atmattpatt**
PHPUnit is published to Packagist and so can be included in projects using Composer's require-dev directive.  Adding a composer.json file will allow phpunit-mockfunction to be publishable to Packagist as well.

### CODE REVIEW

**Comment by tcz** [comment]
Thanks for doing this!

**Comment by atmattpatt** [comment]
Published to Packagist:  https://packagist.org/packages/tcz/phpunit-mockfunction

**Comment by tcz** [comment]
Great, thank you for your contribution Matthew! I should have done this
myself.

**Comment by atmattpatt** [comment]
Np... meant to do it a long time ago but it fell off my radar.  Definitely handy to be able to pull in via composer though

**Comment by tcz** [comment]
Yes, absolutely!

**Pull request merged**
